# Grouping 문제

'풀이'만 수정하기

** 결과 셸은 실행하면 답이 사라져요!! **

In [1]:
# 데이터 불러오기
import pandas as pd

df= pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
df.head(5)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

## Q1.데이터의 각 host_name의 빈도수를 구하고 host_name을 오름차순으로 정렬하여 상위 5개를 출력하라

In [ ]:
# 풀이

In [10]:
#결과
res

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
Name: count, dtype: int64

## Q2.neighbourhood_group의 값에 따른 neighbourhood컬럼 값의 갯수를 구하여라

In [ ]:
# 풀이

In [32]:
#결과

res_df

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

## Q3.neighbourhood_group의 값에 따른 neighbourhood컬럼 값 중 neighbourhood_group그룹의 최댓값들을 출력하라

In [ ]:
# 풀이

In [36]:
# 결과

res_df

  neighbourhood_group    neighbourhood  size
0               Bronx         Woodlawn    70
1            Brooklyn  Windsor Terrace  3920
2           Manhattan     West Village  2658
3              Queens         Woodside   900
4       Staten Island          Woodrow    48

## Q4.neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값을 구하여라

In [41]:
# 풀이

In [40]:
#결과

res_df

                           mean           var    max  min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500    0
Brooklyn             124.383207  34921.719135  10000    0
Manhattan            196.875814  84904.159185  10000    0
Queens                99.517649  27923.130227  10000   10
Staten Island        114.812332  77073.088342   5000   13

## Q5.neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 구하라

In [ ]:
# 풀이

In [44]:
#결과

res_df

       neighbourhood neighbourhood_group       price
0           Allerton               Bronx   87.595238
1      Arden Heights       Staten Island   67.250000
2           Arrochar       Staten Island  115.000000
3            Arverne              Queens  171.779221
4            Astoria              Queens  117.187778
..               ...                 ...         ...
216  Windsor Terrace            Brooklyn  138.993631
217        Woodhaven              Queens   67.170455
218         Woodlawn               Bronx   60.090909
219          Woodrow       Staten Island  700.000000
220         Woodside              Queens   85.097872

[221 rows x 3 columns]

## Q6.neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

In [ ]:
# 풀이

In [49]:
# 결과

res_df

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,NaN,NaN,NaN,NaN
Arden Heights,NaN,NaN,NaN,NaN,67.25
Arrochar,NaN,NaN,NaN,NaN,115.00
Arverne,NaN,NaN,NaN,171.779221,NaN
Astoria,NaN,NaN,NaN,117.187778,NaN
...,...,...,...,...,...
Windsor Terrace,NaN,138.993631,NaN,NaN,NaN
Woodhaven,NaN,NaN,NaN,67.170455,NaN
Woodlawn,60.090909,NaN,NaN,NaN,NaN
Woodrow,NaN,NaN,NaN,NaN,700.00
Woodside,NaN,NaN,NaN,85.097872,NaN

## Q7.neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

In [ ]:
# 풀이

In [53]:
# 결과

res_df

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,-999.000000,-999.0,-999.000000,-999.00
Arden Heights,-999.000000,-999.000000,-999.0,-999.000000,67.25
Arrochar,-999.000000,-999.000000,-999.0,-999.000000,115.00
Arverne,-999.000000,-999.000000,-999.0,171.779221,-999.00
Astoria,-999.000000,-999.000000,-999.0,117.187778,-999.00
...,...,...,...,...,...
Windsor Terrace,-999.000000,138.993631,-999.0,-999.000000,-999.00
Woodhaven,-999.000000,-999.000000,-999.0,67.170455,-999.00
Woodlawn,60.090909,-999.000000,-999.0,-999.000000,-999.00
Woodrow,-999.000000,-999.000000,-999.0,-999.000000,700.00
Woodside,-999.000000,-999.000000,-999.0,85.097872,-999.00

## Q8.데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값을 구하라

In [ ]:
# 풀이

In [56]:
# 결과

res_df

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

# Grouping정답

## Q1. 정답

In [3]:
# 방법 1
gb = df.groupby('host_name').size()
gb = gb.sort_index()  # gb에서 host_name은 index이므로 정렬하기 위해서는 sort_index()를 이용
res = gb.head(5)

# 방법 2
gb = df['host_name'].value_counts()
gb = gb.sort_index()
res = gb.head(5)

## Q2. 정답

In [5]:
# 방법 1
gb = df.groupby(['neighbourhood_group', 'neighbourhood']).size()

# 그룹화된 데이터를 Series를 DataFrame로 변환
# reset_index : 인덱스를 열로 변환, size라는 새로운 열에 그룹의 크기를 나타내는 값
res_df = gb.reset_index(name='size')

# 방법 2
# as_index = False : 그룹화 기준으로 사용한 열들을 인덱스로 사용하지 않고 열로 유지
res_df = df.groupby(['neighbourhood_group', 'neighbourhood'],
                    as_index=False).size()

## Q3. 정답

In [8]:
# neighbourhood_group 및 neighbourhood 열을 기준으로 데이터를 그룹화하고, 각 그룹의 크기를 계산
# 그룹화 결과에서 neighbourhood_group 열을 기준으로 다시 그룹화하고, 각 그룹에서 최대 값을 가진 행을 선택

gb_df = df.groupby(['neighbourhood_group', 'neighbourhood'],
                   as_index=False).size()
res_df = gb_df.groupby('neighbourhood_group', as_index=False).max()

## Q4.정답

In [10]:
res_df = df.groupby('neighbourhood_group')['price'].agg(['mean', 'var', 'max', 'min'])

## Q5.정답

In [12]:
res_df =df.groupby(['neighbourhood', 'neighbourhood_group'], as_index = False)['price'].mean()

## Q6.정답

In [14]:
gb =df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean()
res_df = gb.unstack()

## Q7.정답

In [16]:
gb =df.groupby(['neighbourhood', 'neighbourhood_group'])['price'].mean()
gb_df = gb.unstack()
res_df = gb_df.fillna(-999)

## Q8.정답

In [18]:
queens_df = df[df['neighbourhood_group'] == 'Queens']
res_df = queens_df.groupby('neighbourhood')['price'].agg(['mean', 'var', 'max', 'min'])

# Apply 문제

In [2]:
df =pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv',index_col=0)
df.head(3)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887

## Q1.Income_Category의 카테고리를 apply 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑 후 빈도수를 출력하라

Unknown : N

Less than $40K : a

$40K - $60K : b

$60K - $80K : c

$80K - $120K : d

$120K +’ : e

In [ ]:
# 풀이

In [23]:
# 결과

res

newIncome
a    3561
b    1790
d    1535
c    1402
N    1112
e     727
Name: count, dtype: int64

## Q2.Customer_Age의 값을 이용하여 나이 구간을 AgeState 컬럼으로 정의하라. (0 ~ 9 : 0 , 10 ~ 19 : 10 , 20 ~ 29 : 20 … 각 구간의 빈도수를 출력하라

In [ ]:
# 풀이

In [32]:
# 결과

res

AgeState
20     195
30    1841
40    4561
50    2998
60     530
70       2
Name: count, dtype: int64

## Q3.Credit_Limit 컬럼값이 4500 이상인 경우 1 그외의 경우에는 모두 0으로 하는 newLimit 정의하라. newLimit 각 값들의 빈도수를 출력하라

In [ ]:
# 풀이

In [34]:
# 결과

res

newLimit
1    5096
0    5031
Name: count, dtype: int64

## Q4.Marital_Status 컬럼값이 Married 이고 Card_Category 컬럼의 값이 Platinum인 경우 1 그외의 경우에는 모두 0으로 하는 newState컬럼을 정의하라. newState의 각 값들의 빈도수를 출력하라

In [ ]:
# 풀이

In [41]:
# 결과

res

newState
0    10120
1        7
Name: count, dtype: int64

## Q5.Gender 컬럼값 M인 경우 male F인 경우 female로 값을 변경하여 Gender 컬럼에 새롭게 정의하라. 각 value의 빈도를 출력하라

In [ ]:
# 풀이

In [42]:
# 결과

res

Gender
female    5358
male      4769
Name: count, dtype: int64

# Apply 정답

## Q1.정답

In [4]:
def change(x):
    if x == 'Unknown':
        return 'N'
    elif x == 'Less than $40K':
        return 'a'
    elif x == '$40K - $60K':
        return 'b'
    elif x == '$60K - $80K':
        return 'c'
    elif x == '$80K - $120K':
        return 'd'
    elif x == '$120K +':
        return 'e'


df['newIncome'] = df['Income_Category'].apply(change)
res = df['newIncome'].value_counts()

# Q2.정답

In [6]:
# 방법 1
def age_change(x):
    if 0 <= x < 10:
        return 0
    elif 10 <= x < 20:
        return 10
    elif 20 <= x < 30:
        return 20
    elif 30 <= x < 40:
        return 30
    elif 40 <= x < 50:
        return 40
    elif 50 <= x < 60:
        return 50
    elif 60 <= x < 70:
        return 60
    elif 70 <= x < 80:
        return 70


df['AgeState'] = df['Customer_Age'].apply(age_change)
res = df['AgeState'].value_counts().sort_index()

# 방법 2
df['AgeState'] = df['Customer_Age'].map(lambda x: x // 10 * 10)
res = df['AgeState'].value_counts().sort_index()

## Q3.정답

In [8]:
# 방법 1
def Credit_Limi_change(x):
    if x >= 4500:
        return 1
    else:
        return 0


df['newLimit'] = df['Credit_Limit'].apply(Credit_Limi_change)
res = df['newLimit'].value_counts()

# 방법 2
df['newLimit'] = df['Credit_Limit'].map(lambda x: 1 if x >= 4500 else 0)
res = df['newLimit'].value_counts()

## Q4.정답

In [10]:
def change(data):
    if data['Marital_Status'] == 'Married' and data['Card_Category'] == 'Platinum':
        return 1
    else:
        return 0

    # axis = 1 : 함수 change를 dataframe의 각 행에 적요하기 위해
df['newState'] = df.apply(change, axis = 1)
res = df['newState'].value_counts()

## Q5.정답

In [12]:
def changeGender(x):
    if x == 'M':
        return 'male'
    else:
        return 'female'


df['Gender'] = df.Gender.apply(changeGender)
res = df['Gender'].value_counts()